require "duracloud/version"
require "duracloud/error"

module Duracloud
  autoload :AbstractEntity, "duracloud/abstract_entity"
  autoload :AuditLog, "duracloud/audit_log"
  autoload :BitIntegrityReport, "duracloud/bit_integrity_report"
  autoload :ChunkedContent, "duracloud/chunked_content"
  autoload :Client, "duracloud/client"
  autoload :CLI, "duracloud/cli"
  autoload :Configuration, "duracloud/configuration"
  autoload :Connection, "duracloud/connection"
  autoload :Content, "duracloud/content"
  autoload :ContentManifest, "duracloud/content_manifest"
  autoload :DurastoreRequest, "duracloud/durastore_request"
  autoload :ErrorHandler, "duracloud/error_handler"
  autoload :FastSyncValidation, "duracloud/fast_sync_validation"
  autoload :HasProperties, "duracloud/has_properties"
  autoload :Manifest, "duracloud/manifest"
  autoload :Persistence, "duracloud/persistence"
  autoload :Properties, "duracloud/properties"
  autoload :Request, "duracloud/request"
  autoload :Response, "duracloud/response"
  autoload :RestMethods, "duracloud/rest_methods"
  autoload :Space, "duracloud/space"
  autoload :SpaceAcls, "duracloud/space_acls"
  autoload :Store, "duracloud/store"
  autoload :StorageReport, "duracloud/storage_report"
  autoload :StorageReports, "duracloud/storage_reports"
  autoload :SyncValidation, "duracloud/sync_validation"
  autoload :TSV, "duracloud/tsv"
end
